### ISSUE TITLE
Start-/End-point not in center of elements

### ISSUE THREAD

**Issue by plc-dev** [schaumb/domarrow.js#1]
Hey, thank you for this library. I've been searching all of Stackoverflow before I found this.

However I'm unable to figure out how to set the offset needed to draw the connection from the outside of the div, rather than the center.

I'm guessing I need to add the height and width of the passed elements in this calculation
``` 
var top = (tT + fT) / 2 - W / 2;
var left = (tL + fL) / 2 - H / 2; 
```
But I can't get it to shift and shorten the path correctly. 

Got any heads up?

Cheers

**Comment by schaumb** [comment]
Hi,

There are optional attributes for the `<connection>` tag (fromX, toX, fromY, toY):
```
  <connection from="#d1" to="#d2" color="blue" fromX="0" toX="0" fromY="1" toY="0.6"></connection>
```
These attributes default values are 0.5, which points to the elements center. If you change these ex. to (0, 0), you got the topmost point to the dom element and (1, 1) means the bottom right.

There is an another option too called onlyVisible, which is a valueless option.
```
  <connection from="#d1" to="#d2" color="green" fromX="0" toX="0" onlyVisible></connection>
```
This restrict the arrow that not appear front of the connectable elements, it need to points only to the element border.

I will fill up these examples to the html.

**Comment by plc-dev** [comment]
Great stuff, thanks for the fast response!
