### ISSUE TITLE
Support for Angular2+

### ISSUE THREAD

**Issue by samber** [schaumb/domarrow.js#2]
I just made an Angular library, based on your work ;)

- https://github.com/samber/ngx-domarrow
- https://www.npmjs.com/package/ngx-domarrow
- https://samber.github.io/ngx-domarrow/

![](https://media.giphy.com/media/y8Mz1yj13s3kI/giphy.gif)

**Comment by schaumb** [comment]
Cool! :clap: :thumbsup: :tada: :raised_hands:

![giphy](https://user-images.githubusercontent.com/6457941/72251051-522e8580-35fd-11ea-95e8-240b40a3c41f.gif)
