### ISSUE TITLE
Add readme and license to repository

### ISSUE THREAD

**Issue by msteudtn** [schaumb/domarrow.js#4]
Hello,

Please add a README.MD and a LICENSE to your project. :)

So, people can better understand the scripts and how to use it.

https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-readmes

https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax

thanks.

**Comment by rfaelens** [comment]
Can you please add a LICENSE to your project? This is blocking my own project from release, and may even require me to rip out domarrow.js and replace it with something else....

**Comment by schaumb** [comment]
Thank you for your feedback. I added those 2 files to the repo. I don't have time for the documentation part.

**Comment by rfaelens** [comment]
Awesome!! Thank you so much!
